server:
  port: 8805
  servlet:
    application-display-name: opcda
    context-path: /opcda

spring:
  #时间+8小时
#  jackson:
#    date-format: java.text.SimpleDateFormat    #或正则yyyy-MM-dd HH:mm:ss
#    time-zone: UTC


#  datasource:
#    url: jdbc:mysql://10.27.17.241:3307/imes-platform?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
#    driverClassName: com.mysql.cj.jdbc.Driver
#    username: root
#    password: Root@123
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/opcda?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

mybatis:
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
#logging:
#  level:
#    com.imes.opcda.opc.mapper: debug
logging:
  level:
    org.jinterop: warn
