server:
  port: 8805
  servlet:
    application-display-name: opcda
    context-path: /opcda

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/opcda?serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

mybatis:
  configuration:
    map-underscore-to-camel-case: true

